"""Week 12 — driver analysis: what actually moves support cycle time?

Regression of log(cycle time) on the drivers named in the brief: product, severity, geography,
weekday, and assigned-team workload. Log target because cycle times are strongly right-skewed;
coefficients then read as approximate % effects, and exp(coef)-1 converts them exactly.

Two models are fitted on purpose:
  A — the brief's specification (product + severity + region + weekday + workload)
  B — A plus the dispatch path indicator (did this ticket need a physical part / site visit?)
The gap between their R^2 is the point: most of the variance is structural (does this ticket go
down the parts path at all?), not attributable to who worked it or when.

METHOD VALIDATION. Because the lifecycle data was generated by a documented model
(src/process/process_model.py), the true generating effects are known. The regression should
recover their DIRECTION and ORDERING. Exact magnitudes are not expected to match: the multipliers
act on individual stages, while the regression explains a SUM of stages, which dilutes them. That
comparison is printed and saved — it validates the analysis method itself, which is the part that
transfers to real InGen ticket data.

Run: python -m src.process.drivers
"""
from __future__ import annotations
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

from .process_model import (SEVERITY_SERVICE_MULT, REGION_PARTS_MULT, PRODUCT_REPAIR_MULT)

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data" / "week12"

BASE_SEVERITY = "Medium"
BASE_REGION = "North America"
BASE_PRODUCT = "Fari"


def fit_models():
    df = pd.read_csv(DATA / "ticket_cycle_times.csv", parse_dates=["opened_date"])
    df = df[df["cycle_time_hours"] > 0].copy()
    df["log_cycle"] = np.log(df["cycle_time_hours"])
    df["severity"] = pd.Categorical(df["severity"], ["Critical", "High", BASE_SEVERITY, "Low"])
    df["region"] = pd.Categorical(df["region"])
    df["product"] = pd.Categorical(df["product"])
    df["weekday"] = pd.Categorical(df["weekday"],
                                   ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])

    f_a = (f"log_cycle ~ C(product, Treatment('{BASE_PRODUCT}')) "
           f"+ C(severity, Treatment('{BASE_SEVERITY}')) "
           f"+ C(region, Treatment('{BASE_REGION}')) "
           f"+ C(weekday, Treatment('Monday')) + tier1_queue_on_entry")
    f_b = f_a + " + dispatched"
    m_a = smf.ols(f_a, data=df).fit()
    m_b = smf.ols(f_b, data=df).fit()
    return df, m_a, m_b


def tidy(model, label) -> pd.DataFrame:
    ci = model.conf_int(alpha=0.05)
    out = pd.DataFrame({
        "model": label,
        "term": model.params.index,
        "coef_log": model.params.values,
        "ci_low_log": ci[0].values,
        "ci_high_log": ci[1].values,
        "p_value": model.pvalues.values,
    })
    for c, src in (("effect_pct", "coef_log"), ("ci_low_pct", "ci_low_log"), ("ci_high_pct", "ci_high_log")):
        out[c] = (np.exp(out[src]) - 1) * 100
    out["significant_5pct"] = out["p_value"] < 0.05
    out["term"] = (out["term"]
                   .str.replace(r"C\((\w+), Treatment\('[^']*'\)\)\[T\.([^\]]+)\]", r"\1: \2", regex=True))
    return out.round(4)


def recovery_check(tidy_a: pd.DataFrame) -> pd.DataFrame:
    """Compare recovered directions to the known generating parameters."""
    rows = []

    def truth_dir(mult, base_mult=1.0):
        if mult > base_mult: return "slower"
        if mult < base_mult: return "faster"
        return "none"

    for sev, mult in SEVERITY_SERVICE_MULT.items():
        if sev == BASE_SEVERITY: continue
        r = tidy_a[tidy_a["term"] == f"severity: {sev}"]
        if not len(r): continue
        est = float(r["effect_pct"].iloc[0]); sig = bool(r["significant_5pct"].iloc[0])
        rows.append({"driver": f"severity={sev}", "generating_param": f"service x{mult}",
                     "expected_direction": truth_dir(mult), "estimated_effect_pct": round(est, 1),
                     "estimated_direction": "slower" if est > 0 else "faster",
                     "significant": sig,
                     "direction_recovered": (est > 0) == (mult > 1.0)})
    for reg, mult in REGION_PARTS_MULT.items():
        if reg == BASE_REGION: continue
        r = tidy_a[tidy_a["term"] == f"region: {reg}"]
        if not len(r): continue
        est = float(r["effect_pct"].iloc[0]); sig = bool(r["significant_5pct"].iloc[0])
        rows.append({"driver": f"region={reg}", "generating_param": f"parts lead x{mult}",
                     "expected_direction": truth_dir(mult), "estimated_effect_pct": round(est, 1),
                     "estimated_direction": "slower" if est > 0 else "faster",
                     "significant": sig, "direction_recovered": (est > 0) == (mult > 1.0)})
    for prod, mult in PRODUCT_REPAIR_MULT.items():
        if prod == BASE_PRODUCT: continue
        r = tidy_a[tidy_a["term"] == f"product: {prod}"]
        if not len(r): continue
        est = float(r["effect_pct"].iloc[0]); sig = bool(r["significant_5pct"].iloc[0])
        rows.append({"driver": f"product={prod}", "generating_param": f"repair x{mult}",
                     "expected_direction": truth_dir(mult), "estimated_effect_pct": round(est, 1),
                     "estimated_direction": "slower" if est > 0 else "faster",
                     "significant": sig, "direction_recovered": (est > 0) == (mult > 1.0)})
    return pd.DataFrame(rows)


def main():
    df, m_a, m_b = fit_models()
    ta, tb = tidy(m_a, "A: brief spec"), tidy(m_b, "B: + dispatch path")
    allt = pd.concat([ta, tb], ignore_index=True)
    allt.to_csv(DATA / "driver_effects.csv", index=False)

    print("=== Model A (brief specification) — effects on cycle time, 95% CI ===")
    show = ta[ta["term"] != "Intercept"][["term", "effect_pct", "ci_low_pct", "ci_high_pct",
                                          "p_value", "significant_5pct"]]
    print(show.round(2).to_string(index=False))
    print(f"\nModel A  R^2 = {m_a.rsquared:.3f}   n = {int(m_a.nobs):,}")
    print(f"Model B  R^2 = {m_b.rsquared:.3f}  (adds the dispatch-path indicator)")
    disp = tb[tb["term"] == "dispatched"]
    if len(disp):
        d = disp.iloc[0]
        print(f"  dispatched: {d['effect_pct']:+.1f}% "
              f"[{d['ci_low_pct']:+.1f}%, {d['ci_high_pct']:+.1f}%]  p={d['p_value']:.2g}")

    rec = recovery_check(ta)
    rec.to_csv(DATA / "driver_recovery_check.csv", index=False)
    print("\n=== Method validation: does the regression recover the known generating effects? ===")
    print(rec.to_string(index=False))
    ok = int(rec["direction_recovered"].sum()); tot = len(rec)
    print(f"\nDirections recovered: {ok}/{tot}")
    return allt, rec, m_a, m_b


if __name__ == "__main__":
    main()
